[profile.default]
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
script = 'script'
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
verbosity = 2
cache_path = 'cache'
broadcast = 'broadcast'

[fuzz]
# The number of fuzz runs for fuzz tests
runs = 1000
# The maximum number of test case rejections allowed by proptest, to be
# encountered during usage of `vm.assume` cheatcode. This will be used
# to set the `max_global_rejects` value in proptest test runner config.
# `max_local_rejects` option isn't exposed here since we're not using
# `prop_filter`.
max_test_rejects = 99
# The weight of the dictionary
dictionary_weight = 40
# The flag indicating whether to include values from storage
include_storage = true
# The flag indicating whether to include push bytes values
include_push_bytes = true


[profile.ci.fuzz]
runs = 10_000
max_test_rejects = 9_999
dictionary_weight = 40
include_storage = true
include_push_bytes = true


[rpc_endpoints]
eth = "https://mainnet.infura.io/v3/471b61f9377c47c0a3be9c48286434bc"
polygon = "https://polygon-mainnet.infura.io/v3/471b61f9377c47c0a3be9c48286434bc"

[fmt]
line_length = 100
number_underscore = "thousands"
